* AppImages for Emacs

AppImages for many versions of Emacs, including the latest.

Current versions: 25~29.

AppImages are built on GitHub Actions and distributed in Releases.

I used https://github.com/probonopd/Emacs.AppImage as a starting point. This also applies [[https://github.com/purcell/nix-emacs-ci/tree/master/patches][patches from purcell/nix-emacs-ci]].

Status (tested on Arch Linux):

- 29 :: Works.
  - Default GUI icons are missing.
- 28 :: Works.
  - Default GUI icons are missing.
- 27 :: Works.
  - Default GUI icons are missing.
- 26 :: Works.
  - Default GUI icons are missing.
- 25 :: Works.
  - Default GUI icons are missing.
- 24 ::
  : ./stdio.h:1030:1: error: ‘gets’ undeclared here (not in a function)
  : _GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");
  Also, Ubuntu 18.04 environments (which I previously used for this version and below) are no longer offered by GitHub, so 22~24 will require more work to get working.
- 23.4 ::
  : /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS): In function `__pthread_atfork':
  : /build/glibc-CVJwZb/glibc-2.27/nptl/pthread_atfork.c:51: undefined reference to `__dso_handle'
  : /usr/bin/ld: temacs: hidden symbol `__dso_handle' isn't defined
- 23.2b ::
  : gcc-4.8: error: unrecognized command line option ‘-2.0/’
- 22 :: Make returns error; probably needs ancient Make
- 21 :: no support for x86-64

** Todos
- Enable native compilation for 28+
- Also build for other minor versions
- Enable xwidgets

  Needs [[https://packages.ubuntu.com/focal/libwebkit2gtk-4.0-dev][libwebkit2gtk-4.0-dev]]

- Emacs <= 24

  Emacs <= 23 would need GCC 4.8, it seems.

  cf. https://qiita.com/eurogrve/items/fcb15556bb29289db63e
