* AppImages for Emacs

AppImages for many versions of Emacs, including the latest. They can be downloaded from [[https://github.com/kisaragi-hiu/Emacs.AppImage/releases][Releases]] — the =continuous= release includes the latest build.

I used [[https://github.com/probonopd/Emacs.AppImage][probonopd/Emacs.AppImage]] as a starting point. This also applies [[https://github.com/purcell/nix-emacs-ci/tree/master/patches][patches from purcell/nix-emacs-ci]].

** Why

- This should be a quick way for using latest Emacs on, say, Ubuntu 22.04.
- While developing an Emacs package, it's nice to be able to just open an older version of Emacs and test it locally.

** Status

This is tested on Arch Linux currently.

- AppImages for Emacs 25.3 ~ 29.1 are provided.
- Things appear to work.
- Default GUI icons are missing.
- There is no native compilation. See [[https://github.com/kisaragi-hiu/Emacs.AppImage/issues/4][#4]] for why it's hard and why I don't think it's worth it.

** Caveats

Be aware that no security patches are applied on older versions. In particular, visiting untrusted directories in Emacs < 28.2 is unsafe ([[https://github.com/advisories/GHSA-m57w-hf24-4j3h][CVE-2022-45939]]).

** Status for older versions

I started trying to do these builds in June 2022, initially as a project to build ancient versions of Emacs to tinker with. I gave up after a bit and archived this repository. These are the build notes from back then (mostly).

- 24 ::
  : ./stdio.h:1030:1: error: ‘gets’ undeclared here (not in a function)
  : _GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");
  Also, Ubuntu 18.04 environments (which I previously used for this version and below) are no longer offered by GitHub, so 22~24 will require more work to get working.
- 23.4 ::
  : /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a(pthread_atfork.oS): In function `__pthread_atfork':
  : /build/glibc-CVJwZb/glibc-2.27/nptl/pthread_atfork.c:51: undefined reference to `__dso_handle'
  : /usr/bin/ld: temacs: hidden symbol `__dso_handle' isn't defined
- 23.2b ::
  : gcc-4.8: error: unrecognized command line option ‘-2.0/’
- 22 :: Make returns error; probably needs ancient Make
- 21 :: no support for x86-64

** Todos
- Also build for other minor versions
- Enable xwidgets

  Needs [[https://packages.ubuntu.com/focal/libwebkit2gtk-4.0-dev][libwebkit2gtk-4.0-dev]]

- Emacs <= 24

  Emacs <= 23 would need GCC 4.8, it seems.

  cf. https://qiita.com/eurogrve/items/fcb15556bb29289db63e
