#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
VER=$(find "${HERE}/usr/share/emacs/" -mindepth 1 -maxdepth 1 -printf '%f\n' | sort | head -n 1)
export LD_LIBRARY_PATH=${HERE}/usr/lib/x86_64-linux-gnu/:$HERE/lib/x86_64-linux-gnu/:$HERE/usr/lib/:${HERE}/lib/:$LD_LIBRARY_PATH
export PATH=${HERE}/usr/sbin:${HERE}/usr/bin:$PATH
export EMACSPATH=${HERE}/usr/share/emacs/$VER/
export EMACSDATA=$EMACSPATH/etc
export EMACSDOC=$EMACSPATH/etc
export EMACSLOADPATH=$EMACSPATH/site-lisp:$EMACSPATH/lisp:$EMACSPATH/lisp/emacs-lisp
export INFOPATH=${HERE}/usr/share/info
# FIXME: this uses the host system's gdk-pixbuf loaders.
export GDK_PIXBUF_MODULE_FILE=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
"${HERE}"/usr/bin/emacs "$@"
