#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
VER=$(find "${HERE}/usr/share/emacs/" -mindepth 1 -maxdepth 1 -printf '%f\n' | sort | head -n 1)
export LD_LIBRARY_PATH="$HERE/usr/lib/x86_64-linux-gnu/:$HERE/lib/x86_64-linux-gnu/:$HERE/usr/lib/:$HERE/lib/:$LD_LIBRARY_PATH"
export PATH="$HERE/usr/sbin:$HERE/usr/bin:$PATH"
emacs_dir_bare="$HERE/usr/share/emacs"
emacs_dir="${emacs_dir_bare}/$VER"
export EMACSPATH="${emacs_dir}/"
export EMACSDATA="${emacs_dir}/etc/"
export EMACSDOC="${emacs_dir}/etc/"
export EMACSLOADPATH="${emacs_dir_bare}/site-lisp:${emacs_dir}/site-lisp:${emacs_dir}/lisp:${emacs_dir}/lisp/emacs-lisp"
export INFOPATH="$HERE/usr/share/info"

IFS=":"
read -ra lib_dirs <<<"/usr/lib/:/usr/lib/x86_64-linux-gnu/:/lib/:/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH"
unset IFS

loaders_cache="notfound"
for dir in "${lib_dirs[@]}"; do
    if [ -f "$dir"/gdk-pixbuf-2.0/2.10.0/loaders.cache ]; then
        loaders_cache="$dir"/gdk-pixbuf-2.0/2.10.0/loaders.cache
        export GDK_PIXBUF_MODULE_FILE="$loaders_cache"
        break
    fi
done

if [ "$loaders_cache" = "notfound" ]; then
    echo "gdk-pixbuf loaders cache not found. GTK is likely to crash."
    echo "Text mode (-nw) will still work."
fi

"${HERE}"/usr/bin/emacs "$@"
