name: "Build Emacs"
on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.org"
  workflow_dispatch:

jobs:
  "build":
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        # It might be worth it to switch to GitLab CI so we can use
        # older Ubuntu releases.
        include:
          - emacs: 29.1
            os: ubuntu-22.04
          - emacs: 28.2
            os: ubuntu-20.04
          - emacs: 27.2
            os: ubuntu-20.04
          - emacs: 26.3
            os: ubuntu-20.04
          - emacs: 25.3
            os: ubuntu-20.04
          # - emacs: 24.5
          #   os: ubuntu-18.04
          #  In file included from ../src/config.h:1430:0,
          #                   from md5.c:23:
          # ./stdio.h:1030:1: error: ‘gets’ undeclared here (not in a function)
          #  _GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");
          # - emacs: 24.1
          #   os: ubuntu-18.04
          #
          # /build/glibc-CVJwZb/glibc-2.27/nptl/pthread_atfork.c:51: undefined reference to `__dso_handle'
          # /usr/bin/ld: temacs: hidden symbol `__dso_handle' isn't defined
          #
          # ???
          # - emacs: 23.4
          #   os: ubuntu-18.04
          #
          # make'ing temacs for some reason ends up with this flag:
          #   "-I/usr/include/gio-1 -2.0/"
          # with predictable results.
          # - emacs: 23.2b
          #   os: ubuntu-18.04
          #
          # This probably needs Make 3.81. It relies on some
          # deprecated behavior.
          # https://stackoverflow.com/questions/34562221
          # https://github.com/mirror/make/blob/master/NEWS
          # - os: ubuntu-18.04
          #   emacs: 22.3
          #
          # x86-64 support was added in Emacs 22.
          # - os: ubuntu-18.04
          #   emacs: 21.4a
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install libfuse2 to work around AppImages needing FUSE2
        run: |
          sudo apt install libfuse2
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build Emacs
        run: node build-emacs.mjs ${{ matrix.emacs }}
      - name: Package AppImage
        run: node package-appimage.mjs ${{ matrix.emacs }}
      - uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: build/out/*.AppImage*
          prerelease: true
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: built files ${{ matrix.emacs }}
      #     path: |
      #       build/out/*.AppImage
      #       build/out/*.AppImage.zsync
      #     if-no-files-found: error
      #     # When things actually work we will upload them to Releases
      #     retention-days: 7
