name: "Build Emacs"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  "build":
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        # It might be worth it to switch to GitLab CI so we can use
        # older Ubuntu releases.
        include:
          - emacs: 28.1
            os: ubuntu-20.04
          - emacs: 27.2
            os: ubuntu-20.04
          - emacs: 26.3
            os: ubuntu-20.04
          - emacs: 25.3
            os: ubuntu-20.04
          - emacs: 24.5
            os: ubuntu-18.04
          - emacs: 24.1
            os: ubuntu-18.04
          # "crt*.o not found"
          # This probably needs GCC 4.8.
          - emacs: 23.4
            os: ubuntu-18.04
          - emacs: 23.2b
            os: ubuntu-18.04
          # This probably needs Make 3.81. It relies on some
          # deprecated behavior.
          #
          # https://stackoverflow.com/questions/34562221
          # https://github.com/mirror/make/blob/master/NEWS
          # - os: ubuntu-18.04
          #   emacs: 22.3
          # x86-64 supported was added in Emacs 22.
          # - os: ubuntu-18.04
          #   emacs: 21.4a
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build Emacs
        run: node build-emacs.mjs ${{ matrix.emacs }}
      - name: Package AppImage
        run: node appimage.mjs ${{ matrix.emacs }}
      - uses: actions/upload-artifact@v3
        with:
          name: built files ${{ matrix.emacs }}
          path: build/out/*.AppImage*
          if-no-files-found: error
          # When things actually work we will upload them to Releases
          retention-days: 1
