name: "Build Emacs"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  "build":
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          # - 28.1
          - 27.2
          - 26.3
          # - 25.3
          # - 24.5
          # - 24.2
    steps:
      - uses: actions/checkout@v3
      - name: Build AppImage
        run: node build-emacs.mjs ${{ matrix.emacs_version }}
      - uses: actions/upload-artifact@v3
        with:
          name: built files ${{ matrix.emacs_version }}
          path: build/out/*.AppImage*
          if-no-files-found: error
