name: "Build Emacs"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  "build":
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 28.1
          # - 24.5
          - 24.1
          # "crt*.o not found"
          # This probably needs GCC 4.8.
          # - 23.4
          # - 23.2b
          # This probably needs Make 3.81. It relies on some
          # deprecated behavior, and, of course, because it's an old
          # version, still has it.
          #
          # https://stackoverflow.com/questions/34562221
          # https://github.com/mirror/make/blob/master/NEWS
          # - 22.3
          # x86-64 supported was added in Emacs 22.
          # - 21.4a
          # These build and launch fine, and are only commented out as
          # I test other versions
          #
          # - 27.2
          # - 26.3
          # - 25.3
    steps:
      - uses: actions/checkout@v3
      - name: Build Emacs
        run: node build-emacs.mjs ${{ matrix.emacs_version }}
      - name: Package AppImage
        run: node appimage.mjs ${{ matrix.emacs_version }}
      - uses: actions/upload-artifact@v3
        with:
          name: built files ${{ matrix.emacs_version }}
          path: build/out/*.AppImage*
          if-no-files-found: error
